# Generated by Django 4.2.10 on 2026-04-02 18:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'إضافة', 'verbose_name_plural': 'الإضافات'},
        ),
        migrations.AlterModelOptions(
            name='addongroup',
            options={'verbose_name': 'مجموعة إضافات', 'verbose_name_plural': 'مجموعات الإضافات'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'قسم', 'verbose_name_plural': '2. الأقسام والتصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'صنف', 'verbose_name_plural': '3. قائمة الأصناف'},
        ),
        migrations.AlterModelOptions(
            name='menuitemreview',
            options={'verbose_name': 'تقييم', 'verbose_name_plural': '5. تقييمات الزبائن'},
        ),
        migrations.AlterModelOptions(
            name='menuitemvariant',
            options={'verbose_name': 'حجم/نوع', 'verbose_name_plural': 'أحجام الأصناف'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'ساعة عمل', 'verbose_name_plural': 'ساعات العمل'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'مطعم', 'verbose_name_plural': '1. إدارة المطاعم'},
        ),
        migrations.AlterModelOptions(
            name='tablecall',
            options={'verbose_name': 'طلب طاولة', 'verbose_name_plural': '4. طلبات المساعدة'},
        ),
        migrations.AlterField(
            model_name='addon',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.addongroup', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الإضافة'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم (En)'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الإضافي'),
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='max_selection',
            field=models.IntegerField(default=1, verbose_name='الحد الأقصى للاختيار'),
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='menu.menuitem', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='min_selection',
            field=models.IntegerField(default=0, verbose_name='الحد الأدنى للاختيار'),
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم مجموعة الإضافات'),
        ),
        migrations.AlterField(
            model_name='addongroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم (En)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='أيقونة القسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم القسم (En)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الأساسي'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف (عربي)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف (En)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='صورة الصنف'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الصنف (عربي)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف (En)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='تاغات (Spicy, Vegan...)'),
        ),
        migrations.AlterField(
            model_name='menuitemreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='menuitemreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='menuitemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='menuitemreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم (1-5)'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحجم/النوع'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم (En)'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='close_time',
            field=models.TimeField(verbose_name='وقت الإغلاق'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='مغلق'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_time',
            field=models.TimeField(verbose_name='وقت الافتتاح'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='menu.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف المطعم (عربي)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='وصف المطعم (En)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='font_family',
            field=models.CharField(default='Tajawal', max_length=50, verbose_name='نوع الخط'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='الشعار (Logo)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المطعم (عربي)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المطعم (En)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='رمز QR'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='لون الـ QR'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='اللون الثانوي'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='رابط فريد (Slug)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن')], default='light', max_length=10, verbose_name='وضع الثيم'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='call_type',
            field=models.CharField(choices=[('waiter', 'طلب نادل'), ('bill', 'طلب الحساب'), ('other', 'أخرى')], default='waiter', max_length=10, verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='تمت الاستجابة'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='table_number',
            field=models.CharField(max_length=10, verbose_name='رقم الطاولة'),
        ),
    ]
