# Generated by Django 4.2.10 on 2026-04-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'verbose_name': 'طلب مبيعات', 'verbose_name_plural': '6. سجل المبيعات'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الزبون'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الزبون'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers_text',
            field=models.TextField(blank=True, help_text='Ex: الحجم: كبير، الإضافات: جبنة إضافية', verbose_name='التعديلات (حجم وإضافات)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency_code',
            field=models.CharField(default='ر.س', max_length=10, verbose_name='رمز العملة'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Ex: 9647700000000', max_length=20, verbose_name='رقم الواتساب (للطلبات)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز للتسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
