# Generated by Django 4.2.10 on 2026-04-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_order_options_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='currency_code',
            field=models.CharField(default='د.ع', max_length=10, verbose_name='رمز العملة'),
        ),
    ]
