# Generated by Django 4.2.10 on 2026-04-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_restaurant_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_source',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('nfc', 'NFC')], max_length=10, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='tablecall',
            name='access_source',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('nfc', 'NFC')], max_length=10, verbose_name='المصدر'),
        ),
    ]
