# Generated by Django 4.2.10 on 2026-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_access_source_tablecall_access_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='access_mode',
            field=models.CharField(choices=[('table_specific', 'نظام الطاولات المنفصلة (Per-Table)'), ('general', 'نظام المنيو العام (General Menu)')], default='table_specific', max_length=20, verbose_name='نظام الوصول'),
        ),
    ]
