# Generated by Django 4.2.10 on 2026-08-15 21:58

from django.db import migrations, models
import django.db.models.deletion


def seed_platform_settings(apps, schema_editor):
    PlatformSettings = apps.get_model('menu', 'PlatformSettings')
    PlatformSettings.objects.get_or_create(
        singleton_key=1,
        defaults={
            'platform_name': 'شركة برنتو للحلول الذكية',
            'platform_website_url': 'https://www.facebook.com/',
            'show_platform_branding': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_enterprisecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('platform_name', models.CharField(default='شركة برنتو للحلول الذكية', max_length=255, verbose_name='اسم المنصة / الشركة')),
                ('platform_logo_url', models.URLField(blank=True, help_text='رابط مباشر لشعار برنتو (PNG/SVG).', verbose_name='رابط شعار المنصة')),
                ('platform_website_url', models.URLField(blank=True, help_text='فيسبوك، إنستغرام، واتساب، أو الموقع الرسمي.', verbose_name='رابط صفحة برنتو')),
                ('show_platform_branding', models.BooleanField(default=True, verbose_name='إظهار شريط الحقوق في المنيو')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المنصة (Branding)',
                'verbose_name_plural': 'إعدادات المنصة (Branding)',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hide_platform_branding',
            field=models.BooleanField(default=False, help_text='للمطاعm المؤسسية التي دفعت لإزالة «صُمم بواسطة برنتو» من المنيو.', verbose_name='إخفاء شعار المنصة (Enterprise)'),
        ),
        migrations.RunPython(seed_platform_settings, migrations.RunPython.noop),
    ]
