# Generated by Django 4.2.10 on 2026-09-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_analytics_promotions_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'مطعم (Tenant)', 'verbose_name_plural': '1. إدارة المطاعm — SaaS'},
        ),
        migrations.RenameIndex(
            model_name='authhandoff',
            new_name='menu_authha_expires_665b71_idx',
            old_name='menu_authha_expires_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='menu_catego_tenant__1a657a_idx',
            old_name='menu_catego_tenant__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='menu_catego_tenant__1c490d_idx',
            old_name='menu_catego_tenant__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='experiencereview',
            new_name='menu_experi_tenant__b8f13b_idx',
            old_name='menu_experi_tenant__j1k2l3_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_menuit_tenant__2a612a_idx',
            old_name='menu_menuit_tenant_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='menu_order_tenant__23b6bb_idx',
            old_name='menu_order_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='restaurant',
            new_name='menu_restau_slug_e49ad0_idx',
            old_name='menu_restau_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='restaurant',
            new_name='menu_restau_is_acti_5541d5_idx',
            old_name='menu_restau_active_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='restauranttable',
            new_name='menu_restau_tenant__1a8982_idx',
            old_name='menu_resttab_tenant_active_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant', verbose_name='المطعm (Tenant)'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='menu.restaurant', verbose_name='المطعm (Tenant)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز للتسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.restaurant', verbose_name='المطعm (Tenant)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modifiers_text',
            field=models.TextField(blank=True, verbose_name='التعديلات (حجم وإضافات)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_covers/', verbose_name='صورة الغلاف (Banner)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='hide_platform_branding',
            field=models.BooleanField(default=False, help_text='للمطاعم المؤسسية التي دفعت لإزالة «صُمم بواسطة برنتو» من المنيو.', verbose_name='إخفاء شعار المنصة (Enterprise)'),
        ),
        migrations.AlterField(
            model_name='tablecall',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='table_calls', to='menu.restaurant', verbose_name='المطعm (Tenant)'),
        ),
    ]
